[package]
name = "hello_gl"
version = "0.2.0"
authors = ["yongqin wang <jcyongqin@outlook.com>"]


[features]
gl_debug = ["libgl/debug"]


[dependencies]
libgl = { path = "../libgl" }
image = "0.19.0"
cgmath = "0.16.1"

[dependencies.sdl2]
version = "0.31.0"
features = ["bundled", "static-link"]


